version: "2.3"

services:
  tensorflow_py3_build:
    build: 
        context: .
        dockerfile: Dockerfile
    image: my_tensorflow:latest
      
  tensorflow_py3:
    depends_on: 
      - tensorflow_py3_build
    image: my_tensorflow:latest
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - /home/bs0826/dev:/tf/notebooks/dev
      - /home/bs0826/workspace/:/tf/notebooks/workspace
      - /mnt/data:/tf/notebooks/data
    # environment:
    # allow specifying a subset of GPUs to be used
    # - CUDA_VISIBLE_DEVICES
    restart: always
  # tensorflow_py2:
  #   image: "tensorflow/tensorflow:latest-gpu-jupyter"
  #   runtime: nvidia
  #   # environment:
  #   #   - JUPYTER_PORT=8899
  #   ports:
  #     - "8899:8899"
  #   volumes:
  #     - /home/bs0826/dev:/tf/notebooks/dev
  #     - /home/bs0826/workspace/:/tf/notebooks/workspace
  #     - /mnt/data:/tf/notebooks/data
  #   # environment:
  #     # allow specifying a subset of GPUs to be used
  #     # - CUDA_VISIBLE_DEVICES
  #   restart: always
